/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HealthMetricsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getBloodSugar"
      | "getBmi"
      | "getHealthScore"
      | "getHeartRate"
      | "getTimestamp"
      | "getTotalUsers"
      | "getUserAtIndex"
      | "hasHealthData"
      | "protocolId"
      | "submitHealthData"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "HealthDataSubmitted" | "HealthScoreCalculated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getBloodSugar",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getBmi", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getHealthScore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHeartRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserAtIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasHealthData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitHealthData",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getBloodSugar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBmi", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getHealthScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHeartRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasHealthData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitHealthData",
    data: BytesLike
  ): Result;
}

export namespace HealthDataSubmittedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HealthScoreCalculatedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HealthMetrics extends BaseContract {
  connect(runner?: ContractRunner | null): HealthMetrics;
  waitForDeployment(): Promise<this>;

  interface: HealthMetricsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getBloodSugar: TypedContractMethod<[], [string], "view">;

  getBmi: TypedContractMethod<[], [string], "view">;

  getHealthScore: TypedContractMethod<[], [string], "view">;

  getHeartRate: TypedContractMethod<[], [string], "view">;

  getTimestamp: TypedContractMethod<[], [bigint], "view">;

  getTotalUsers: TypedContractMethod<[], [bigint], "view">;

  getUserAtIndex: TypedContractMethod<[index: BigNumberish], [string], "view">;

  hasHealthData: TypedContractMethod<[], [boolean], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  submitHealthData: TypedContractMethod<
    [
      _bmi: BytesLike,
      _bmiProof: BytesLike,
      _bloodSugar: BytesLike,
      _bloodSugarProof: BytesLike,
      _heartRate: BytesLike,
      _heartRateProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getBloodSugar"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getBmi"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getHealthScore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getHeartRate"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalUsers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserAtIndex"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "hasHealthData"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitHealthData"
  ): TypedContractMethod<
    [
      _bmi: BytesLike,
      _bmiProof: BytesLike,
      _bloodSugar: BytesLike,
      _bloodSugarProof: BytesLike,
      _heartRate: BytesLike,
      _heartRateProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "HealthDataSubmitted"
  ): TypedContractEvent<
    HealthDataSubmittedEvent.InputTuple,
    HealthDataSubmittedEvent.OutputTuple,
    HealthDataSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "HealthScoreCalculated"
  ): TypedContractEvent<
    HealthScoreCalculatedEvent.InputTuple,
    HealthScoreCalculatedEvent.OutputTuple,
    HealthScoreCalculatedEvent.OutputObject
  >;

  filters: {
    "HealthDataSubmitted(address,uint256)": TypedContractEvent<
      HealthDataSubmittedEvent.InputTuple,
      HealthDataSubmittedEvent.OutputTuple,
      HealthDataSubmittedEvent.OutputObject
    >;
    HealthDataSubmitted: TypedContractEvent<
      HealthDataSubmittedEvent.InputTuple,
      HealthDataSubmittedEvent.OutputTuple,
      HealthDataSubmittedEvent.OutputObject
    >;

    "HealthScoreCalculated(address,uint256)": TypedContractEvent<
      HealthScoreCalculatedEvent.InputTuple,
      HealthScoreCalculatedEvent.OutputTuple,
      HealthScoreCalculatedEvent.OutputObject
    >;
    HealthScoreCalculated: TypedContractEvent<
      HealthScoreCalculatedEvent.InputTuple,
      HealthScoreCalculatedEvent.OutputTuple,
      HealthScoreCalculatedEvent.OutputObject
    >;
  };
}
